### ISSUE TITLE
[Android] Use react-native-image-crop-picker to read the photo path error

### ISSUE THREAD

**Issue by skyliwq** [edeckers/react-native-blob-courier#66]
Android 10

```
020-12-11 19:33:16.012 1042-3167/com.blobtest.app E/AndroidRuntime: FATAL EXCEPTION: Thread-16
    Process: com.kelapp, PID: 1042
    java.io.FileNotFoundException: file:/storage/emulated/0/Android/data/com.kelapp/files/Pictures/d2f82461-1f50-4b46-b4f5-61ae2b8d2d5a.jpg: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at okio.Okio.source(Okio.java:168)
        at okhttp3.RequestBody$3.writeTo(RequestBody.java:119)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
        at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
        at io.deckers.blob_courier.BlobCourierProgressRequest.writeTo(BlobCourierProgressRequest.kt:33)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at io.deckers.blob_courier.BlobCourierModuleKt$startBlobUpload$1.invoke(BlobCourierModule.kt:156)
        at io.deckers.blob_courier.BlobCourierModuleKt$startBlobUpload$1.invoke(Unknown Source:0)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
    	Suppressed: java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.close(Http1Codec.java:307)
        at okio.ForwardingSink.close(ForwardingSink.java:47)
        at okio.RealBufferedSink.close(RealBufferedSink.java:248)
        at okio.ForwardingSink.close(ForwardingSink.java:47)
        at okio.RealBufferedSink.close(RealBufferedSink.java:248)
        at kotlin.io.CloseableKt.closeFinally(Closeable.kt:60)
        		... 19 more
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7737)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        	... 24 more
```

**Comment by edeckers** [comment]
@skyliwq can you elaborate on what caused this? Something related to the library, or something else?

**Comment by skyliwq** [comment]
Uploading files, involving local uploads or photo uploads, systems below Android 10 can work properly, the access path of more than Android 10 is empty, and Android: requestLegacyExternalStorage=“true" in the application still cannot solve the problem.

**Comment by edeckers** [comment]
Thanks, I'll look into it!

**Comment by edeckers** [comment]
Moving this discussion to #67 .
